In [1]:
# Day 56 - Introduction to Jupyter Notebook & NumPy
# -----------------------------------------------
# Step 1: Import NumPy
import numpy as np

In [2]:
# Step 2: Create basic arrays
a = np.array([1, 2, 3, 4, 5])
b = np.array([[1, 2, 3], [4, 5, 6]])


In [3]:
# Step 3: Display arrays
print("1D Array:\n", a)
print("\n2D Array:\n", b)

1D Array:
 [1 2 3 4 5]

2D Array:
 [[1 2 3]
 [4 5 6]]


In [4]:

# Step 4: Array Attributes
print("\nArray 'a' Attributes:")
print("Shape:", a.shape)
print("Dimensions:", a.ndim)
print("Data type:", a.dtype)


Array 'a' Attributes:
Shape: (5,)
Dimensions: 1
Data type: int64


In [5]:
print("\nArray 'b' Attributes:")
print("Shape:", b.shape)
print("Dimensions:", b.ndim)
print("Data type:", b.dtype)


Array 'b' Attributes:
Shape: (2, 3)
Dimensions: 2
Data type: int64


In [6]:
# Step 5: Create arrays using NumPy functions
zeros_arr = np.zeros((2, 3))
ones_arr = np.ones((3, 2))
range_arr = np.arange(0, 10, 2)

In [7]:

print("\nZeros Array:\n", zeros_arr)
print("\nOnes Array:\n", ones_arr)
print("\nRange Array:\n", range_arr)


Zeros Array:
 [[0. 0. 0.]
 [0. 0. 0.]]

Ones Array:
 [[1. 1.]
 [1. 1.]
 [1. 1.]]

Range Array:
 [0 2 4 6 8]


In [8]:
# Step 6: Broadcasting example
x = np.array([1, 2, 3])
y = np.array([10])
result = x + y
print("\nBroadcasting Example (x + y):", result)


Broadcasting Example (x + y): [11 12 13]
